name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend
        
      - name: Build
        run: npm run build
        working-directory: ./frontend
        env:
          VITE_STORAGE_PROVIDER: ${{ secrets.VITE_STORAGE_PROVIDER }}
          VITE_GOOGLE_SHEETS_API_KEY: ${{ secrets.VITE_GOOGLE_SHEETS_API_KEY }}
          VITE_GOOGLE_SHEET_ID: ${{ secrets.VITE_GOOGLE_SHEET_ID }}
          VITE_GOOGLE_SHEET_ID_CUANTITATIVOS: ${{ secrets.VITE_GOOGLE_SHEET_ID_CUANTITATIVOS }}
          VITE_GOOGLE_SHEET_ID_AMBIENTALES_INCENDIOS_FORESTALES: ${{ secrets.VITE_GOOGLE_SHEET_ID_AMBIENTALES_INCENDIOS_FORESTALES }}
          VITE_GOOGLE_SHEET_ID_AMBIENTALES_RESIDUOS_SOLIDOS: ${{ secrets.VITE_GOOGLE_SHEET_ID_AMBIENTALES_RESIDUOS_SOLIDOS }}
          VITE_GOOGLE_SHEET_ID_AMBIENTALES_EMISIONES: ${{ secrets.VITE_GOOGLE_SHEET_ID_AMBIENTALES_EMISIONES }}
          VITE_GOOGLE_SHEET_ID_AMBIENTALES_ENERGIA: ${{ secrets.VITE_GOOGLE_SHEET_ID_AMBIENTALES_ENERGIA }}
          VITE_GOOGLE_SHEET_ID_AMBIENTALES_AREAS_NATURALES: ${{ secrets.VITE_GOOGLE_SHEET_ID_AMBIENTALES_AREAS_NATURALES }}
          VITE_GOOGLE_SHEET_ID_ECONOMICOS_INGRESO_TOTAL: ${{ secrets.VITE_GOOGLE_SHEET_ID_ECONOMICOS_INGRESO_TOTAL }}
          VITE_GOOGLE_SHEET_ID_ECONOMICOS_EGRESO_TOTAL: ${{ secrets.VITE_GOOGLE_SHEET_ID_ECONOMICOS_EGRESO_TOTAL }}
          VITE_GOOGLE_SHEET_ID_ECONOMICOS_PEA: ${{ secrets.VITE_GOOGLE_SHEET_ID_ECONOMICOS_PEA }}
          VITE_GOOGLE_SHEET_ID_ECONOMICOS_PIBE: ${{ secrets.VITE_GOOGLE_SHEET_ID_ECONOMICOS_PIBE }}
          VITE_GOOGLE_SHEET_ID_ECONOMICOS_ITAEE: ${{ secrets.VITE_GOOGLE_SHEET_ID_ECONOMICOS_ITAEE }}
          VITE_GOOGLE_SHEET_ID_SOCIALES_DESOCUPACION: ${{ secrets.VITE_GOOGLE_SHEET_ID_SOCIALES_DESOCUPACION }}
          VITE_GOOGLE_SHEET_ID_SOCIALES_MARGINACION: ${{ secrets.VITE_GOOGLE_SHEET_ID_SOCIALES_MARGINACION }}
          VITE_GOOGLE_SHEET_ID_SOCIALES_IDH: ${{ secrets.VITE_GOOGLE_SHEET_ID_SOCIALES_IDH }}
          VITE_GOOGLE_SHEET_ID_SOCIALES_REZAGO_SOCIAL: ${{ secrets.VITE_GOOGLE_SHEET_ID_SOCIALES_REZAGO_SOCIAL }}
          VITE_GOOGLE_SHEET_ID_SOCIALES_INDICE_GINI: ${{ secrets.VITE_GOOGLE_SHEET_ID_SOCIALES_INDICE_GINI }}
          VITE_GOOGLE_SHEET_ID_SOCIALES_POBLACION: ${{ secrets.VITE_GOOGLE_SHEET_ID_SOCIALES_POBLACION }}
          VITE_GOOGLE_SHEET_ID_GOB_SATISFACCION_FEDERAL: ${{ secrets.VITE_GOOGLE_SHEET_ID_GOB_SATISFACCION_FEDERAL }}
          VITE_GOOGLE_SHEET_ID_GOB_SATISFACCION_ESTATAL: ${{ secrets.VITE_GOOGLE_SHEET_ID_GOB_SATISFACCION_ESTATAL }}
          VITE_GOOGLE_SHEET_ID_GOB_IGOPP: ${{ secrets.VITE_GOOGLE_SHEET_ID_GOB_IGOPP }}
          VITE_GOOGLE_SHEET_ID_GOB_BIPE: ${{ secrets.VITE_GOOGLE_SHEET_ID_GOB_BIPE }}
          VITE_GOOGLE_SHEET_ID_GOB_ITDIF: ${{ secrets.VITE_GOOGLE_SHEET_ID_GOB_ITDIF }}
          VITE_GOOGLE_SHEET_ID_GOB_ICI: ${{ secrets.VITE_GOOGLE_SHEET_ID_GOB_ICI }}
          VITE_GOOGLE_SHEET_ID_GOB_PBRSED: ${{ secrets.VITE_GOOGLE_SHEET_ID_GOB_PBRSED }}
          VITE_GOOGLE_SHEET_ID_PRESUPUESTO_PRESUPUESTO_ESTATAL: ${{ secrets.VITE_GOOGLE_SHEET_ID_PRESUPUESTO_PRESUPUESTO_ESTATAL }}
          VITE_GOOGLE_SHEET_ID_PRESUPUESTO_FINANCIAMIENTOS: ${{ secrets.VITE_GOOGLE_SHEET_ID_PRESUPUESTO_FINANCIAMIENTOS }}
          VITE_GOOGLE_SHEET_ID_PRESUPUESTO_PROGRAMAS: ${{ secrets.VITE_GOOGLE_SHEET_ID_PRESUPUESTO_PROGRAMAS }}
          VITE_GOOGLE_SHEET_ID_RANKING_INTERNACIONAL: ${{ secrets.VITE_GOOGLE_SHEET_ID_RANKING_INTERNACIONAL }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist